# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.posterior <- function(y, p, prior, burn_in, N, random_seed, verbose) {
    .Call(`_pyinar_posterior`, y, p, prior, burn_in, N, random_seed, verbose)
}

.generalized_median <- function(pred) {
    .Call(`_pyinar_generalized_median`, pred)
}

.predictive_distribution_prop <- function(model, h) {
    .Call(`_pyinar_predictive_distribution_prop`, model, h)
}

.predictive_distribution_mc <- function(model, h, replications) {
    .Call(`_pyinar_predictive_distribution_mc`, model, h, replications)
}

